name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install nextflow
        uses: nf-core/setup-nextflow@v1
      - uses: eWaterCycle/setup-singularity@v7
      - name: Install champagne
        run: |
          python -m pip install --upgrade pip setuptools
          pip install .[dev,test]
      - uses: actions/cache/restore@v3
        id: cache-containers-restore
        with:
          path: singularity
          key: ${{ runner.os }}-containers

      - name: Test stub run
        run: |
          champagne run -profile ci_stub,github -stub

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: nextflow-log
          path: .nextflow.log

      - uses: actions/cache/save@v3
        id: cache-containers-save
        with:
          path: singularity
          key: ${{ steps.cache-cache-containers-restore.outputs.cache-primary-key }}
